// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1602930000);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1602930122);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1602877070);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1602929879);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1602930245);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 16 Oct 2020 17:24:07 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1602930097);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"11341741-51ff-4da3-9872-44bd2bb5dcb5\",\"default-theme@mozilla.org\":\"335bcaa5-ea28-476d-ac4c-6c19afd77dc6\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1602931462);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "8e8381d8-e68e-4e33-aa0b-1dc6bdf66f1");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1602931468);
user_pref("places.history.expiration.transient_current_max_pages", 58799);
user_pref("security.sandbox.plugin.tempDirSuffix", "d978757b-9145-444d-b45a-875f959d9c68");
user_pref("services.blocklist.pinning.checked", 1602929882);
user_pref("services.settings.clock_skew_seconds", 2);
user_pref("services.settings.last_etag", "\"1602921443410\"");
user_pref("services.settings.last_update_seconds", 1602929882);
user_pref("services.settings.main.hijack-blocklists.last_check", 1602929882);
user_pref("services.settings.main.language-dictionaries.last_check", 1602929882);
user_pref("services.settings.main.sites-classification.last_check", 1602929882);
user_pref("services.settings.security.onecrl.checked", 1602929882);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1602931465);
user_pref("toolkit.telemetry.cachedClientID", "dda16009-9f7d-4c81-bc6d-0383cf88dae2");
user_pref("toolkit.telemetry.prompted", 2);
