// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1604748901);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1604749022);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1604748659);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1604748779);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1604749177);
user_pref("browser.cache.disk.capacity", 215040);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "KZ");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 04 Nov 2020 15:24:28 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1604748911);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"11341741-51ff-4da3-9872-44bd2bb5dcb5\",\"default-theme@mozilla.org\":\"335bcaa5-ea28-476d-ac4c-6c19afd77dc6\",\"yandex@search.mozilla.org\":\"44019e63-2869-4373-abed-c4b3bc18e7fb\",\"google@search.mozilla.org\":\"1b92564d-25db-458c-9301-4b06c07ee5c1\",\"ddg@search.mozilla.org\":\"c1f6f88c-9498-47d8-be89-ec320a342252\",\"ozonru@search.mozilla.org\":\"8810940e-c296-42bd-b2e3-11739aada44d\",\"priceru@search.mozilla.org\":\"6b10cc20-af40-4fcc-a1d9-c6ce58f12c99\",\"wikipedia@search.mozilla.org\":\"0e33dffc-5cb0-43d1-8c92-cc50202d0e2b\",\"mailru@search.mozilla.org\":\"e474f4f0-048b-4336-8158-b08843aaca1f\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1604749171);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "8e8381d8-e68e-4e33-aa0b-1dc6bdf66f1");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1604749311);
user_pref("places.history.expiration.transient_current_max_pages", 41583);
user_pref("security.sandbox.plugin.tempDirSuffix", "d978757b-9145-444d-b45a-875f959d9c68");
user_pref("services.blocklist.pinning.checked", 1604749792);
user_pref("services.settings.clock_skew_seconds", -1010);
user_pref("services.settings.last_etag", "\"1604739435964\"");
user_pref("services.settings.last_update_seconds", 1604749792);
user_pref("services.settings.main.hijack-blocklists.last_check", 1604749792);
user_pref("services.settings.main.language-dictionaries.last_check", 1604749792);
user_pref("services.settings.main.sites-classification.last_check", 1604749792);
user_pref("services.settings.security.onecrl.checked", 1604749792);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1602931465);
user_pref("toolkit.telemetry.cachedClientID", "dda16009-9f7d-4c81-bc6d-0383cf88dae2");
user_pref("toolkit.telemetry.prompted", 2);
